name: "my-firtst-job"

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkou repo
          users: actions/checkout@v4

        - name: Welcome message
          run: echo "Hello world"
          
        - name: List files
          run: ls
        - name: ReadFile
          run: cat README.md    
