name: "Generate ASCII ARTWORK"

on: push

jobs:
    asci_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Checkout repo files
          run: ls

        - name: Execute Shell Script
          run: |
              sudo chmod +x ascii.sh
              ./ascii.sh

        


          
      
