name: "Generate ASCII ARTWORK"

on:
     push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          uses: sudo apt-get install cowsay -y

        - name: Execute cowsay cmd
          run: cowsay -f dragon "hello world" >> dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 30

    test_job:
        runs-on: ubuntu-latest
        steps:
        - name: Sleep 10 seconds
          run: sleep 10
        - name: test file exist
          run: grep -i "hello" dragon.txt
          

              

        


          
      
